Repository NativeScript/nativescript-background-http, pull requests merged in 2018-02, with the labels that each got.

#107 Snapshot-friendly
  nativescript-background-http/.gitignore
  nativescript-background-http/background-http.android.ts
  nativescript-background-http/package.json
  nativescript-background-http/tsconfig.json
Labels: ♥ community PR

#106 Implemented Canceling uploads
  examples/SimpleBackgroundHttp/app/main-page.ts
  nativescript-background-http/background-http.android.ts
  nativescript-background-http/background-http.ios.ts
  nativescript-background-http/index.d.ts
  nativescript-background-http/package.json
  nativescript-background-http/platforms/android/AndroidManifest.xml
  package.json
Labels: feature, ♥ community PR

#113 docs: add development workflow
  DevelopmentWorkflow.md
Labels: feature, new PR
